-   id: django-migrations-exist
    name: check model changes have migrations
    description: 'Enforce that any model changes are accompanied by staged migrations'
    entry: migrations-exist.py
    language: python
    types: [python]
    files: /models(/.*)?.py$